[package]
name = "rustcast"
version = "0.1.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]

[dependencies]
lame = "0.1"
lewton = "0.6.2"
ogg = "0.5.1"
tiny_http = { path = "vendor/tiny-http" }
